package com.jayway.maven.plugins.android.phase05compile;

import org.apache.maven.artifact.Artifact;

import java.io.File;
import java.util.Set;

/** Various helper methods for dealing with Android Native makefiles.
 * @author Johan Lindquist
 */
public class MakefileHelper {

    /** Creates an Android Makefile based on the specified set of static library dependency artifacts.
     *
     * @param outputDir Directory to resolve artifact locations relative to.  Makefiles contain relative paths
     * @param artifacts The list of (static library) dependency artifacts to create the Makefile from
     * @return The created Makefile
     */
    public static String createMakefileFromArtifacts(File outputDir, Set<Artifact> artifacts) {

        StringBuilder sb = new StringBuilder("# Generated by Android Maven Plugin\n");
        sb.append( "LOCAL_PATH := $(call my-dir)\n" );

        for ( Artifact artifact : artifacts ) {

            sb.append( "#\n" );
            sb.append( "# Group ID: " );
            sb.append( artifact.getGroupId() );
            sb.append( '\n' );
            sb.append( "# Artifact ID: " );
            sb.append( artifact.getArtifactId());
            sb.append( '\n' );
            sb.append( "# Version: " );
            sb.append( artifact.getVersion() );
            sb.append( '\n' );
            sb.append( "include $(CLEAR_VARS)" );
            sb.append( '\n' );
            sb.append( "LOCAL_MODULE    := " );
            sb.append( artifact.getArtifactId() );
            sb.append( '\n' );
            sb.append( "LOCAL_SRC_FILES := " );
            sb.append( resolveRelativePath( outputDir, artifact ) );
            sb.append( '\n' );
/*
            sb.append( "LOCAL_EXPORT_C_INCLUDES := " );
            sb.append( "");
            sb.append( '\n' );
*/

            sb.append( "include $(PREBUILT_STATIC_LIBRARY)\n" );
        }
        return sb.toString();
    }

    /** Resolves the relative path of the specified artifact
     *
     * @param outputDirectory
     * @param artifact
     * @return
     */
    private static String resolveRelativePath( File outputDirectory, Artifact artifact ) {
        return ".." + artifact.getFile().getAbsolutePath();
    }

    /** Creates a list of artifacts suitable for use in the LOCAL_STATIC_LIBRARIES variable in an Android makefile
     *
     * @param resolvedstaticLibraryArtifacts
     * @return
     */
    public static String createStaticLibraryList( Set<Artifact> resolvedstaticLibraryArtifacts ) {
        StringBuilder sb = new StringBuilder();
        for ( Artifact resolvedstaticLibraryArtifact : resolvedstaticLibraryArtifacts ) {
            sb.append( resolvedstaticLibraryArtifact.getArtifactId() );
            sb.append( " " );

        }
        return sb.toString();
    }
}
