= Contributing

We welcome any contribtuion in the forms of feedback on social media, helping out on stackoverflow whatever. This 
page however focuses on how to contribute either documentation or source code. All of it is contained in the same git 
repository.

== Prerequisites

You will have to either know git already or learn it. You will love it!

== Contributing Flow

Once to know how to use git you

* fork the repostiory to your own github account
* create a branch for your specific work (separate issues or changes should be separate branches)
* verify it all builds and looks right (see the Building documentation for more on that)
* send a pull request

== Documentation Contributions

All docs are written in asciidoc and should be located in 'src/site/asciidoc'. The will be published with the Maven site 
for each release and also available on the github user interface directly. You can even edit them in the github interface.

== Code Contributions

Just have to be fixing an issue or enhancing the plugin somehow. Even a javadoc spelling fix is not too small to submit.
The only thing you need to check is that you can build the plugin, because we enforce things like codestyle and so on 
automatically.
