= Using the NDK 

This document describes how to use the android-maven-plugin to create native libraries. There are a number of example
projects setup within the plugin code base.

WARNING: This functionality will be removed and is migrated to the android-ndk-maven-plugin.

== Features

Currently, the Android Maven Plugins NDK mojo supports the following scenarios when 
developing with native code:

* Compile native shared library (.so) for use by other projects
** Can depend on other native shared/static libraries
** Declared as dependencies in the pom.xml 
* Include native library in your APK
** Defined as a dependency in the pom.xml
** Defined as 'mixed' with the APK code
* Compile a native static library (.a) to be shared with other projects
** Shares header files as part of project artifacts
** Used by projects depending on static library as part of the build

== Prerequisites

* Android NDK installed
* Set the `ANDROID_NDK_HOME` the the root directory of your NDK installation. 

For example:

----
REM Windows
SET ANDROID_NDK_HOME=C:\opt\android-ndk-r7b
----

or

----
# Linux
export ANDROID_NDK_HOME=$HOME/opt/android-ndk-r7b
----

These settings are best to persist by adding as permanent environment variables.

== Configuring Your Maven Project

There are many variations on how the NDK usage can be integrated e.g.

  * Native Code Lives in the APK project
  * Native Code Lives in the APKLIB project

== Native Code Lives in the APK project

=== Setup pom.xml 

The following instructions apply to the setup of a apk with a native library.

=== Cleanup

The NDK does not compile into the `target` directory but into `obj` and `libs` so 
they need to be cleaned as well:

----
<plugin>
  <artifactId>maven-clean-plugin</artifactId>
  <configuration>
    <filesets>
      <fileset>
        <directory>libs</directory>
      </fileset>
      <fileset>
        <directory>obj</directory>
      </fileset>
    </filesets>
  </configuration>
</plugin>
----

=== Build Setup

Native build is activated by the `ndk-build` goal. Also the plugin need to know the location of the 
NDK installation unless configured via the environment variable.

----
<plugin>
  <groupId>com.simpligility.maven.plugins.android</groupId>
  <artifactId>android-maven-plugin</artifactId>
  <goals>
    <goal>ndk-build</goal>
  </goals>
  <configuration>
    <ndk>
      <path>${env.ANDROID_NDK_HOME}</path>
    </ndk>
  </configuration>
  <extensions>true</extensions>
</plugin>
----

=== Execute Build

Use the following two command to build.

----
mvn android:ndk-build
mvn install
----

== Native Code Lives in the APKLIB project ==

The following instructions apply to the setup of a APK Library project with a native library. 
Note that the Library must have the same name as the artifact id. You can not add multiple 
native Libraries to a single APKLIB.

=== Cleanup

You should add a `maven-clean-plugin` section like the one described above.

=== Library POM

The POM should be set up as `<packaging>apklib</packaging>`. Taking it from there you set the
 configuration as follow:

----
<plugin>
  <groupId>com.simpligility.maven.plugins</groupId>
  <artifactId>android-maven-plugin</artifactId>
  <goals>
    <goal>ndk-build</goal>
  </goals>
  <configuration>
    <deleteConflictingFiles>true</deleteConflictingFiles>
    <attachNativeArtifacts>true</attachNativeArtifacts>
    <clearNativeArtifacts>false</clearNativeArtifacts>
    <sign>
      <debug>false</debug>
    </sign>
  </configuration>
  <extensions>true</extensions>
</plugin>
----

=== Application POM

Add an apklib dependency:

----
<dependency>
  <groupId>my.package</groupId>
  <artifactId>Native-Lib</artifactId>
  <version>0.0.0</version>
  <type>apklib</type>
</dependency>
----

=== Execute Build

Use the following two command to build.

----
mvn --projects ../Native-Lib android:ndk-build
mvn install
----
