= Releasing 

This should be of no interest to developers of Android applications. This is for 
those developers of the Android Maven Plugin who perform releases of the plugin.

== General

You have to be able to do full build of the plugin including site creation and integration tests: 

----
mvn clean install -P it
mvn site
----

Beyond that you need all the setup to deploy to the Central repository. Follow the 
http://central.sonatype.org[setup instructions]. In addition you need to have permissions to deploy to the 
groupId.

For site deployment you need to add your github credentials into settings.xml for the site deployment 
to github pages as part of the release build to work:

----
<server>
  <id>githb</id>
  <username>yourname</username>
  <password>yourpassword</password>
</server>
---

== Getting Ready

In order to release the plugin you need to have fully passing builds including integration tests 
and site creation.

.Deploy a SNAPSHOT version

If you want to make available a binary version of Android Maven Plugin for someone to test, 
before making a proper release, deploy a SNAPSHOT version.

Don't worry, it will sit in a separate directory structure from the proper releases. 
It won't end up on Maven Central.

Do it!
To perform the SNAPSHOT release:

  cd ~/maven-android-plugin
  mvn clean deploy -P official-release

That should deploy the artifacts directly to the SNAPSHOT repo on http://oss.sonatype.org. 

. Perform a RELEASE

This is the real deal. A release will be synced to Maven Central after a few minutes, and then 
there is NO way to have it removed. Make sure it passes all tests!

Do it!

To perform the release:

  cd ~/maven-android-plugin
  export MAVEN_OPTS='-Xmx256m' 
  mvn release:prepare release:perform


With the right setup this will

* create a tag and push it to github
* prepare and deploy everything for the plugin release (jar, sources, javadoc..) to OSSRH
* release the staging repository on OSSRH so the plugin is automatically synced to the Central Repository
* deploy the site to github pages 

Check here http://repo1.maven.org/maven2/com/simpligility/maven/plugins/android-maven-plugin/

Announce on the Maven Android Developers list and the Maven developers and users mailing lists

To obtain a correct permalink to the announcement email, go to the Maven Android Developers group, 
open the announcement post and click the little chain/link icon to the right.
